//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ShoesOrders = new HashSet<ShoesOrder>();
        }
    
        public int customerId { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        public string customerFName { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name")]
        public string customerLName { get; set; }

        [Required(ErrorMessage = "Please Enter Address")]
        public string customerAddress { get; set; }

        [Required(ErrorMessage = "Please Enter Phone")]
        public string customerPhone { get; set; }

        [EmailAddress]
        public string customerEmail { get; set; }

        public string customerState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoesOrder> ShoesOrders { get; set; }
    }
}
