//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShoesOrder
    {
        public int orderId { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> customerId { get; set; }


        [Required(ErrorMessage = "Please enter the price")]
        [Range(0, 9999, ErrorMessage = "Enter price between 0 to 9999")]
        public Nullable<decimal> orderPrice { get; set; }

        [Required(ErrorMessage = "Please enter the quantity")]
        [Range(0, 999, ErrorMessage = "Enter price between 0 to 999")]
        public Nullable<int> quantity { get; set; }
        public string shoesName { get; set; }
        public string comments { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
